#!/bin/sh -e

cd build_unix

../dist/configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sharedstatedir=/var \
    --docdir=/usr/share/doc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info

make
make DESTDIR="$1" install
