#!/bin/sh -e

cd build_unix

../dist/configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sharedstatedir=/var

make
make DESTDIR="$1" install

# Cleanup after a poor Makefile that doesn't respect docdir
rm -rf "$1/usr/docs"
